### ISSUE TITLE
borken on mac

### ISSUE THREAD

**Issue by LampCo** [hipeopeo/auternos#1]
bitchass
```lexscobey@Lexs-MacBook-Pro auternos % python3 auternos.py 
Traceback (most recent call last):
  File "auternos.py", line 11, in <module>
    driver = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.

lexscobey@Lexs-MacBook-Pro auternos % 
```

**Comment by hipeopeo** [comment]
Did you point to the proper Chrom(ium)e binary?

For Chrome (not Chromium) on macOS, change
`options.binary_location = "/path/to/bin/Chromium"`
to
`options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"`

**Comment by LampCo** [comment]
ok that fixed it
